export const ADMIN_LIST_REQUEST = 'ADMIN_LIST_REQUEST';
export const ADMIN_LIST_SUCCESS = 'ADMIN_LIST_SUCCESS';
export const ADMIN_LIST_FAIL = 'ADMIN_LIST_FAIL';

export const ADMIN_LIST_BYID_REQUEST = 'ADMIN_LIST_BYID_REQUEST';
export const ADMIN_LIST_BYID_SUCCESS = 'ADMIN_LIST_BYID_SUCCESS';
export const ADMIN_LIST_BYID_FAIL = 'ADMIN_LIST_BYID_FAIL';

export const ADMIN_FORGOT_PASSWORD_REQUEST = 'ADMIN_FORGOT_PASSWORD_REQUEST';
export const ADMIN_FORGOT_PASSWORD_SUCCESS = 'ADMIN_FORGOT_PASSWORD_SUCCESS';
export const ADMIN_FORGOT_PASSWORD_FAIL = 'ADMIN_FORGOT_PASSWORD_FAIL';

export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';

export const ADMIN_SIGNUP_REQUEST = 'ADMIN_SIGNUP_REQUEST';
export const ADMIN_SIGNUP_SUCCESS = 'ADMIN_SIGNUP_SUCCESS';
export const ADMIN_SIGNUP_FAIL = 'ADMIN_SIGNUP_FAIL';

export const ADMIN_UPDATE_REQUEST = 'ADMIN_UPDATE_REQUEST';
export const ADMIN_UPDATE_SUCCESS = 'ADMIN_UPDATE_SUCCESS';
export const ADMIN_UPDATE_FAIL = 'ADMIN_UPDATE_FAIL';

export const ADMIN_DELETE_REQUEST = 'ADMIN_DELETE_REQUEST';
export const ADMIN_DELETE_SUCCESS = 'ADMIN_DELETE_SUCCESS';
export const ADMIN_DELETE_FAIL = 'ADMIN_DELETE_FAIL';
