export const CUSTOMER_LIST_REQUEST = 'CUSTOMER_LIST_REQUEST';
export const CUSTOMER_LIST_SUCCESS = 'CUSTOMER_LIST_SUCCESS';
export const CUSTOMER_LIST_FAIL = 'CUSTOMER_LIST_FAIL';

export const CUSTOMER_LIST_BYID_REQUEST = 'CUSTOMER_LIST_BYID_REQUEST';
export const CUSTOMER_LIST_BYID_SUCCESS = 'CUSTOMER_LIST_BYID_SUCCESS';
export const CUSTOMER_LIST_BYID_FAIL = 'CUSTOMER_LIST_BYID_FAIL';

export const CUSTOMER_FORGOT_PASSWORD_REQUEST = 'CUSTOMER_FORGOT_PASSWORD_REQUEST';
export const CUSTOMER_FORGOT_PASSWORD_SUCCESS = 'CUSTOMER_FORGOT_PASSWORD_SUCCESS';
export const CUSTOMER_FORGOT_PASSWORD_FAIL = 'CUSTOMER_FORGOT_PASSWORD_FAIL';

export const CUSTOMER_LOGIN_REQUEST = 'CUSTOMER_LOGIN_REQUEST';
export const CUSTOMER_LOGIN_SUCCESS = 'CUSTOMER_LOGIN_SUCCESS';
export const CUSTOMER_LOGIN_FAIL = 'CUSTOMER_LOGIN_FAIL';

export const CUSTOMER_SIGNUP_REQUEST = 'CUSTOMER_SIGNUP_REQUEST';
export const CUSTOMER_SIGNUP_SUCCESS = 'CUSTOMER_SIGNUP_SUCCESS';
export const CUSTOMER_SIGNUP_FAIL = 'CUSTOMER_SIGNUP_FAIL';

export const CUSTOMER_UPDATE_REQUEST = 'CUSTOMER_UPDATE_REQUEST';
export const CUSTOMER_UPDATE_SUCCESS = 'CUSTOMER_UPDATE_SUCCESS';
export const CUSTOMER_UPDATE_FAIL = 'CUSTOMER_UPDATE_FAIL';

export const CUSTOMER_DELETE_REQUEST = 'CUSTOMER_DELETE_REQUEST';
export const CUSTOMER_DELETE_SUCCESS = 'CUSTOMER_DELETE_SUCCESS';
export const CUSTOMER_DELETE_FAIL = 'CUSTOMER_DELETE_FAIL';
