export const CUSTOMIZE_PACKAGES_LIST_REQUEST = 'CUSTOMIZE_PACKAGES_LIST_REQUEST';
export const CUSTOMIZE_PACKAGES_LIST_SUCCESS = 'CUSTOMIZE_PACKAGES_LIST_SUCCESS';
export const CUSTOMIZE_PACKAGES_LIST_FAIL = 'CUSTOMIZE_PACKAGES_LIST_FAIL';

export const CUSTOMIZE_PACKAGES_LIST_BYID_REQUEST = 'CUSTOMIZE_PACKAGES_LIST_BYID_REQUEST';
export const CUSTOMIZE_PACKAGES_LIST_BYID_SUCCESS = 'CUSTOMIZE_PACKAGES_LIST_BYID_SUCCESS';
export const CUSTOMIZE_PACKAGES_LIST_BYID_FAIL = 'CUSTOMIZE_PACKAGES_LIST_BYID_FAIL';

export const CUSTOMIZE_PACKAGES_ADD_REQUEST = 'CUSTOMIZE_PACKAGES_ADD_REQUEST';
export const CUSTOMIZE_PACKAGES_ADD_SUCCESS = 'CUSTOMIZE_PACKAGES_ADD_SUCCESS';
export const CUSTOMIZE_PACKAGES_ADD_FAIL = 'CUSTOMIZE_PACKAGES_ADD_FAIL';

export const CUSTOMIZE_PACKAGES_UPDATE_STATUS_REQUEST = 'CUSTOMIZE_PACKAGES_UPDATE_STATUS_REQUEST';
export const CUSTOMIZE_PACKAGES_UPDATE_STATUS_SUCCESS = 'CUSTOMIZE_PACKAGES_UPDATE_STATUS_SUCCESS';
export const CUSTOMIZE_PACKAGES_UPDATE_STATUS_FAIL = 'CUSTOMIZE_PACKAGES_UPDATE_STATUS_FAIL';

export const CUSTOMIZE_PACKAGES_DELETE_REQUEST = 'CUSTOMIZE_PACKAGES_DELETE_REQUEST';
export const CUSTOMIZE_PACKAGES_DELETE_SUCCESS = 'CUSTOMIZE_PACKAGES_DELETE_SUCCESS';
export const CUSTOMIZE_PACKAGES_DELETE_FAIL = 'CUSTOMIZE_PACKAGES_DELETE_FAIL';
