export const FEEDBACK_LIST_REQUEST = 'FEEDBACK_LIST_REQUEST';
export const FEEDBACK_LIST_SUCCESS = 'FEEDBACK_LIST_SUCCESS';
export const FEEDBACK_LIST_FAIL = 'FEEDBACK_LIST_FAIL';

export const FEEDBACK_ADD_REQUEST = 'FEEDBACK_ADD_REQUEST';
export const FEEDBACK_ADD_SUCCESS = 'FEEDBACK_ADD_SUCCESS';
export const FEEDBACK_ADD_FAIL = 'FEEDBACK_ADD_FAIL';
