export const PACKAGES_LIST_REQUEST = 'PACKAGES_LIST_REQUEST';
export const PACKAGES_LIST_SUCCESS = 'PACKAGES_LIST_SUCCESS';
export const PACKAGES_LIST_FAIL = 'PACKAGES_LIST_FAIL';

export const PACKAGES_LIST_BYID_REQUEST = 'PACKAGES_LIST_BYID_REQUEST';
export const PACKAGES_LIST_BYID_SUCCESS = 'PACKAGES_LIST_BYID_SUCCESS';
export const PACKAGES_LIST_BYID_FAIL = 'PACKAGES_LIST_BYID_FAIL';

export const PACKAGES_ADD_REQUEST = 'PACKAGES_ADD_REQUEST';
export const PACKAGES_ADD_SUCCESS = 'PACKAGES_ADD_SUCCESS';
export const PACKAGES_ADD_FAIL = 'PACKAGES_ADD_FAIL';

export const PACKAGES_UPDATE_REQUEST = 'PACKAGES_UPDATE_REQUEST';
export const PACKAGES_UPDATE_SUCCESS = 'PACKAGES_UPDATE_SUCCESS';
export const PACKAGES_UPDATE_FAIL = 'PACKAGES_UPDATE_FAIL';

export const PACKAGES_DELETE_REQUEST = 'PACKAGES_DELETE_REQUEST';
export const PACKAGES_DELETE_SUCCESS = 'PACKAGES_DELETE_SUCCESS';
export const PACKAGES_DELETE_FAIL = 'PACKAGES_DELETE_FAIL';
