export const PAYMENT_LIST_REQUEST = 'PAYMENT_LIST_REQUEST';
export const PAYMENT_LIST_SUCCESS = 'PAYMENT_LIST_SUCCESS';
export const PAYMENT_LIST_FAIL = 'PAYMENT_LIST_FAIL';

export const PAYMENT_LIST_BYID_REQUEST = 'PAYMENT_LIST_BYID_REQUEST';
export const PAYMENT_LIST_BYID_SUCCESS = 'PAYMENT_LIST_BYID_SUCCESS';
export const PAYMENT_LIST_BYID_FAIL = 'PAYMENT_LIST_BYID_FAIL';

export const PAYMENT_ADD_REQUEST = 'PAYMENT_ADD_REQUEST';
export const PAYMENT_ADD_SUCCESS = 'PAYMENT_ADD_SUCCESS';
export const PAYMENT_ADD_FAIL = 'PAYMENT_ADD_FAIL';
