export const RESERVE_PACKAGES_LIST_REQUEST = 'RESERVE_PACKAGES_LIST_REQUEST';
export const RESERVE_PACKAGES_LIST_SUCCESS = 'RESERVE_PACKAGES_LIST_SUCCESS';
export const RESERVE_PACKAGES_LIST_FAIL = 'RESERVE_PACKAGES_LIST_FAIL';

export const RESERVE_PACKAGES_LIST_BYID_REQUEST = 'RESERVE_PACKAGES_LIST_BYID_REQUEST';
export const RESERVE_PACKAGES_LIST_BYID_SUCCESS = 'RESERVE_PACKAGES_LIST_BYID_SUCCESS';
export const RESERVE_PACKAGES_LIST_BYID_FAIL = 'RESERVE_PACKAGES_LIST_BYID_FAIL';

export const RESERVE_PACKAGES_DELETE_REQUEST = 'RESERVE_PACKAGES_DELETE_REQUEST';
export const RESERVE_PACKAGES_DELETE_SUCCESS = 'RESERVE_PACKAGES_DELETE_SUCCESS';
export const RESERVE_PACKAGES_DELETE_FAIL = 'RESERVE_PACKAGES_DELETE_FAIL';
